[window]
width = 800
height = 800

[[pipeline]]
shader_type = "fragment"
label = "Fragment Shader"
entry_point = "fs_main"
file = "fragment.wgsl"

[spectrum]
min_frequency = 20.0
max_frequency = 4000.0
sampling_rate = 44100